document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("	<head>");
document.writeln("		<meta charset=\'utf-8\'>");
document.writeln("		<title></title>");
document.writeln("");
document.writeln("	</head>");
document.writeln("	<body>");
document.writeln("		");
document.writeln("			<div class=\'w1100 ma oh\'>");
document.writeln("				<div class=\'footer_main oh\'>");
document.writeln("					<div id=\'main_le\'>");
document.writeln("						<a href=\'../index.html\'>");
document.writeln("							<h1>");
document.writeln("								<img src=\'../style/img/logo2.gif\' />");
document.writeln("							</h1>");
document.writeln("						</a>");
document.writeln("");
document.writeln("						<h4>4 0 0 - 8 0 0 - 3 6 5</h4>");
document.writeln("						<h5>单位官网 : <a href=\'http://www.cn-invest.cn\'>http://www.cn-invest.cn</a></h5>");
document.writeln("						<h5>总部地址 : 北京市朝阳区光华路4号东方梅地亚中心A座</h5>");
document.writeln("					</div>");
document.writeln("					<div id=\'main_ri\'>");
document.writeln("						<img src=\'../style/img/code.gif\' />");
document.writeln("					</div>");
document.writeln("				</div>");
document.writeln("				<div class=\'mt10\' id=\'record\'>");
document.writeln("					<a href=\'##\' class=\'db tc f12\'>京ICP备19027158</a>");
document.writeln("				</div>");
document.writeln("			</div>");
document.writeln("		</footer>");
document.writeln("	</body>");
document.writeln("</html>");
document.writeln("");