document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("	<head>");
document.writeln("		<meta charset=\'utf-8\'>");
document.writeln("		<title></title>");
document.writeln("	</head>");
document.writeln("	<body>");
document.writeln("			<ul class=\'Clearfix w1100 ma oh\'>");
document.writeln("				<li class=\'fl tc f14\' id=\'serviceNavLi1\'>");
document.writeln("					<a href=\'##\'>项目申报</a>");
document.writeln("				</li>");
document.writeln("				<li class=\'fl tc f14\' id=\'serviceNavLi2\'>");
document.writeln("					<a href=\'##\'>乡村振兴</a>");
document.writeln("				</li>");
document.writeln("				<li class=\'fl tc f14\' id=\'serviceNavLi3\'>");
document.writeln("					<a href=\'##\'>田园综合体</a>");
document.writeln("				</li>");
document.writeln("				<li class=\'fl tc f14\' id=\'serviceNavLi4\'>");
document.writeln("					<a href=\'##\'>现代农业</a>");
document.writeln("				</li>");
document.writeln("				<li class=\'fl tc f14\' id=\'serviceNavLi5\'>");
document.writeln("					<a href=\'../page/services2.html\'>产业园规划</a>");
document.writeln("				</li>");
document.writeln("				<li class=\'fl tc f14\' id=\'serviceNavLi6\'>");
document.writeln("					<a href=\'##\'>资金申请</a>");
document.writeln("				</li>");
document.writeln("				<li class=\'fl tc f14\' id=\'serviceNavLi7\'>");
document.writeln("					<a href=\'##\'>乡村旅游</a>");
document.writeln("				</li>");
document.writeln("				<li class=\'fl tc f14\' id=\'borderR\'>");
document.writeln("					<a href=\'##\'>市场调研</a>");
document.writeln("				</li>");
document.writeln("			</ul>");
document.writeln("			<div class=\'pa\' id=\'returnHome\'>");
document.writeln("				<a href=\'../index.html\' class=\'db w h\' title=\'返回首页\'></a>");
document.writeln("			</div>");
document.writeln("	</body>");
document.writeln("</html>");
document.writeln("");