document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("	<head>");
document.writeln("		<meta charset=\'utf-8\'>");
document.writeln("		<title></title>");
document.writeln("	</head>");
document.writeln("	<body>");
document.writeln("		<div id=\'subPageNav\' class=\'fl\'>");
document.writeln("			<ul class=\'Clearfix w\'>");
document.writeln("				<li class=\'mt10\' id=\'li1\'>");
document.writeln("					<a href=\'../index.html\' class=\'tc f12 c000\'>");
document.writeln("						<p>首&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;页</p>");
document.writeln("						<p id=\'p2\'>HOME</p>");
document.writeln("					</a>");
document.writeln("				</li>");
document.writeln("				<li class=\'mt10\' id=\'li2\'>");
document.writeln("					<a href=\'../page/services1.html\' class=\'tc f12 c000\'>");
document.writeln("						<p>业务中心</p>");
document.writeln("						<p id=\'p2\'>SERVICES</p>");
document.writeln("					</a>");
document.writeln("				</li>");
document.writeln("				<li class=\'mt10\' id=\'li3\'>");
document.writeln("					<a href=\'../page/NewsCenter.html\' class=\'tc f12 c000\'>");
document.writeln("						<p>资讯中心</p>");
document.writeln("						<p id=\'p2\'>NEWS CENTER</p>");
document.writeln("					</a>");
document.writeln("				</li>");
document.writeln("				<li class=\'mt10\' id=\'li4\'>");
document.writeln("					<a href=\'../page/Policies.html\' class=\'tc f12 c000\'>");
document.writeln("						<p>农业政策</p>");
document.writeln("						<p id=\'p2\'>POLICLES</p>");
document.writeln("					</a>");
document.writeln("				</li>");
document.writeln("				<li class=\'mt10\' id=\'li5\'>");
document.writeln("					<a href=\'##\' class=\'tc f12 c000\'>");
document.writeln("						<p>案例展示</p>");
document.writeln("						<p id=\'p2\'>CASES</p>");
document.writeln("					</a>");
document.writeln("				</li>");
document.writeln("				<li class=\'mt10\' id=\'li6\'>");
document.writeln("					<a href=\'../page/Agritech.html\' class=\'tc f12 c000\'>");
document.writeln("						<p>技术发展</p>");
document.writeln("						<p id=\'p2\'>AGRITECH</p>");
document.writeln("					</a>");
document.writeln("				</li>");
document.writeln("				<li class=\'mt10\' id=\'li7\'>");
document.writeln("					<a href=\'##\' class=\'tc f12 c000\'>");
document.writeln("						<p>关于我们</p>");
document.writeln("						<p id=\'p2\'>ABOUT US</p>");
document.writeln("					</a>");
document.writeln("				</li>");
document.writeln("			</ul>");
document.writeln("		</div>");
document.writeln("	</body>");
document.writeln("</html>");
document.writeln("");