document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("	<head>");
document.writeln("		<meta charset=\'utf-8\'>");
document.writeln("		<title></title>");
document.writeln("	</head>");
document.writeln("	<body>");
document.writeln("		<div class=\'w1100 ma oh\'>");
document.writeln("			<h2 class=\'c000 tc mt50 mb40 pr\' id=\'splitLine\'>您的需求</h2>");
document.writeln("			<form action=\'\' class=\'pr ma oh\' id=\'form1\'>");
document.writeln("				<input type=\'text\' class=\'fl\' placeholder=\'联系人:\' />");
document.writeln("				<input type=\'text\' class=\'fr\' placeholder=\'职务:\' />");
document.writeln("				<input type=\'text\' class=\'fl\' placeholder=\'电话:\' />");
document.writeln("				<input type=\'text\' class=\'fr\' placeholder=\'邮箱:\' />");
document.writeln("				<textarea onfocus=\'document.getElementById(\'note\').style.display=\'none\'\' onblur=\'if(value==\'\')document.getElementById(\'note\').style.display=\'block\'\'></textarea>");
document.writeln("				<div id=\'note\' class=\'note\'>");
document.writeln("					<font color=\'#999\'>您的需求:</font>");
document.writeln("				</div>");
document.writeln("				<input type=\'submit\' onclick=\'return false;\' id=\'submit\' class=\'db f24 tac cp\' />");
document.writeln("				<!-- <button type=\'button\' class=\'db f24 cfff tac cp\'>提交</button> -->");
document.writeln("			</form>");
document.writeln("		</div>");
document.writeln("	</body>");
document.writeln("</html>");